### ISSUE TITLE
Upgrade the ES 5 test to us es 5.5.0 and make it the default version

### ISSUE THREAD

**Issue by godber** [terascope/teraslice-integration-tests#14]
These tests explicitly test against the ES 5.0 release:

https://github.com/terascope/teraslice-integration-tests/blob/master/spec/docker-compose-es5.0.yml#L21

They should test the ES 5.5.0 release at this point.  But perhaps parameterizing things would be better.  Maybe just using `elasticsearch:5` instead if parameterizing it a hassle.

Also, ES5 should be the default for the integration tests now, instead of 2.

**Comment by erik-stephens** [comment]
Fixed in terascope/teraslice#482

**Comment by godber** [comment]
This was done in the version of the integration tests that were integrated to the main teraslice project.
